<a href="https://colab.research.google.com/github/jackgit106/My-Python-Project-Repository/blob/main/3rdWorksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
numbers = pd.Series([10, 20, 30, 40])
print(numbers)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
}
print(data)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}

In [ ]:
isinstance(df, pd.DataFrame)

True

In [ ]:
!pip --version

pip 24.1.2 from /usr/local/lib/python3.12/dist-packages/pip (python 3.12)

In [ ]:
pip install package_name

Collecting package_name
  Downloading package_name-0.1.tar.gz (782 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: package_name
  Building wheel for package_name (setup.py) ... done
  Created wheel for package_name: filename=package_name-0.1-py3-none-any.whl size=1229 sha256=d1a637f83069c1265545be3d2491c4b0fa751528b6232205049ed257324322de
  Stored in directory: /root/.cache/pip/wheels/7e/a6/f5/ce521d547a4606ce65febcdcefd1c847622c6451dce9f3e8e5
Successfully built package_name
Installing collected packages: package_name
Successfully installed package_name-0.1

In [ ]:
!pip install --upgrade package_name

Requirement already satisfied: package_name in /usr/local/lib/python3.12/dist-packages (0.1)

In [ ]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.3)
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 41.1 MB/s eta 0:00:00
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.3
    Uninstalling pandas-2.2.3:
      Successfully uninstalled pandas-2.2.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.0.5 which is incompatible.
Successfully installed pandas-3.0.5

In [ ]:
import pandas as pd
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
!pip install pandas matplotlib seaborn --quiet

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option("display.max_rows", 10)
sns.set(style="whitegrid")

In [ ]:
print("Setup complete")

Setup complete

In [ ]:
from google. colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from google.colab import files
import pandas as pd
uploaded = files.upload()           # you choose "student.csv from choose files – below tab
full_path = '/content/student.csv'  # match the name shown after upload.

Saving student.csv to student (1).csv

In [ ]:
df = pd.read_csv('/content/student.csv')             # file that appears on the left
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df[['name', 'class']].head()

         name  class
0    John Deo   Four
1    Max Ruin  Three
2      Arnold  Three
3  Krish Star   Four
4   John Mike   Four

In [ ]:
df[['name', 'class', 'gender']].head()

         name  class  gender
0    John Deo   Four  female
1    Max Ruin  Three    male
2      Arnold  Three    male
3  Krish Star   Four  female
4   John Mike   Four  female

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/student.csv')  # upload file from MyDrive
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
row_data = df.iloc[2]
print(row_data)

id             3
name      Arnold
class      Three
mark          55
gender      male
Name: 2, dtype: object

In [ ]:
subset_data = df.iloc[0:2, 0:2]    # to see by row and column
print(subset_data)

   id      name
0   1  John Deo
1   2  Max Ruin

In [ ]:
print(df.columns)

Index(['id', 'name', 'class', 'mark', 'gender'], dtype='object')

In [ ]:
for i, col in enumerate(df.columns):
  print(i, col)

0 id
1 name
2 class
3 mark
4 gender

In [ ]:
# To see row values and index for each row: (i = index)
for i, row in df.iterrows():    # iterate over rows
   print(i, row.to_dict())    #turns a row (a Series) into a {column: value} dictionary.

0 {'id': 1, 'name': 'John Deo', 'class': 'Four', 'mark': 75, 'gender': 'female'}
1 {'id': 2, 'name': 'Max Ruin', 'class': 'Three', 'mark': 85, 'gender': 'male'}
2 {'id': 3, 'name': 'Arnold', 'class': 'Three', 'mark': 55, 'gender': 'male'}
3 {'id': 4, 'name': 'Krish Star', 'class': 'Four', 'mark': 60, 'gender': 'female'}
4 {'id': 5, 'name': 'John Mike', 'class': 'Four', 'mark': 60, 'gender': 'female'}
5 {'id': 6, 'name': 'Alex John', 'class': 'Four', 'mark': 55, 'gender': 'male'}
6 {'id': 7, 'name': 'My John Rob', 'class': 'Fifth', 'mark': 78, 'gender': 'male'}
7 {'id': 8, 'name': 'Asruid', 'class': 'Five', 'mark': 85, 'gender': 'male'}
8 {'id': 9, 'name': 'Tes Qry', 'class': 'Six', 'mark': 78, 'gender': nan}
9 {'id': 10, 'name': 'Big John', 'class': 'Four', 'mark': 55, 'gender': 'female'}
10 {'id': 11, 'name': 'Ronald', 'class': 'Six', 'mark': 89, 'gender': 'female'}
11 {'id': 12, 'name': 'Recky', 'class': 'Six', 'mark': 94, 'gender': 'female'}
12 {'id': 13, 'name': 'Kty', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
13 {'id': 14, 'name': 'Bigy', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
14 {'id': 15, 'name': 'Tade Row', 'class': nan, 'mark': 88, 'gender': 'male'}
15 {'id': 16, 'name': 'Gimmy', 'class': 'Four', 'mark': 88, 'gender': 'male'}
16 {'id': 17, 'name': 'Tumyu', 'class': 'Six', 'mark': 54, 'gender': 'male'}
17 {'id': 18, 'name': 'Honny', 'class': 'Five', 'mark': 75, 'gender': 'male'}
18 {'id': 19, 'name': 'Tinny', 'class': 'Nine', 'mark': 18, 'gender': 'male'}
19 {'id': 20, 'name': 'Jackly', 'class': 'Nine', 'mark': 65, 'gender': 'female'}
20 {'id': 21, 'name': 'Babby John', 'class': 'Four', 'mark': 69, 'gender': 'female'}
21 {'id': 22, 'name': 'Reggid', 'class': 'Seven', 'mark': 55, 'gender': 'female'}
22 {'id': 23, 'name': 'Herod', 'class': 'Eight', 'mark': 79, 'gender': 'male'}
23 {'id': 24, 'name': 'Tiddy Now', 'class': 'Seven', 'mark': 78, 'gender': 'male'}
24 {'id': 25, 'name': 'Giff Tow', 'class': 'Seven', 'mark': 88, 'gender': 'male'}
25 {'id': 26, 'name': 'Crelea', 'class': 'Seven', 'mark': 79, 'gender': 'male'}
26 {'id': 27, 'name': nan, 'class': 'Three', 'mark': 81, 'gender': nan}
27 {'id': 28, 'name': 'Rojj Base', 'class': 'Seven', 'mark': 86, 'gender': 'female'}
28 {'id': 29, 'name': 'Tess Played', 'class': 'Seven', 'mark': 55, 'gender': 'male'}
29 {'id': 30, 'name': 'Reppy Red', 'class': 'Six', 'mark': 79, 'gender': 'female'}
30 {'id': 31, 'name': 'Marry Toeey', 'class': 'Four', 'mark': 88, 'gender': 'male'}
31 {'id': 32, 'name': 'Binn Rott', 'class': 'Seven', 'mark': 90, 'gender': 'female'}
32 {'id': 33, 'name': 'Kenn Rein', 'class': 'Six', 'mark': 96, 'gender': 'female'}
33 {'id': 34, 'name': 'Gain Toe', 'class': 'Seven', 'mark': 69, 'gender': 'male'}
34 {'id': 35, 'name': 'Rows Noump', 'class': 'Six', 'mark': 88, 'gender': 'female'}

In [ ]:
# To see row values and index for each row: (i = index)
for i, column in df.iterrows():    # iterate over rows
   print(i, column.to_dict())    #turns a row (a Series) into a {column: value} dictionary.

0 {'id': 1, 'name': 'John Deo', 'class': 'Four', 'mark': 75, 'gender': 'female'}
1 {'id': 2, 'name': 'Max Ruin', 'class': 'Three', 'mark': 85, 'gender': 'male'}
2 {'id': 3, 'name': 'Arnold', 'class': 'Three', 'mark': 55, 'gender': 'male'}
3 {'id': 4, 'name': 'Krish Star', 'class': 'Four', 'mark': 60, 'gender': 'female'}
4 {'id': 5, 'name': 'John Mike', 'class': 'Four', 'mark': 60, 'gender': 'female'}
5 {'id': 6, 'name': 'Alex John', 'class': 'Four', 'mark': 55, 'gender': 'male'}
6 {'id': 7, 'name': 'My John Rob', 'class': 'Fifth', 'mark': 78, 'gender': 'male'}
7 {'id': 8, 'name': 'Asruid', 'class': 'Five', 'mark': 85, 'gender': 'male'}
8 {'id': 9, 'name': 'Tes Qry', 'class': 'Six', 'mark': 78, 'gender': nan}
9 {'id': 10, 'name': 'Big John', 'class': 'Four', 'mark': 55, 'gender': 'female'}
10 {'id': 11, 'name': 'Ronald', 'class': 'Six', 'mark': 89, 'gender': 'female'}
11 {'id': 12, 'name': 'Recky', 'class': 'Six', 'mark': 94, 'gender': 'female'}
12 {'id': 13, 'name': 'Kty', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
13 {'id': 14, 'name': 'Bigy', 'class': 'Seven', 'mark': 88, 'gender': 'female'}
14 {'id': 15, 'name': 'Tade Row', 'class': nan, 'mark': 88, 'gender': 'male'}
15 {'id': 16, 'name': 'Gimmy', 'class': 'Four', 'mark': 88, 'gender': 'male'}
16 {'id': 17, 'name': 'Tumyu', 'class': 'Six', 'mark': 54, 'gender': 'male'}
17 {'id': 18, 'name': 'Honny', 'class': 'Five', 'mark': 75, 'gender': 'male'}
18 {'id': 19, 'name': 'Tinny', 'class': 'Nine', 'mark': 18, 'gender': 'male'}
19 {'id': 20, 'name': 'Jackly', 'class': 'Nine', 'mark': 65, 'gender': 'female'}
20 {'id': 21, 'name': 'Babby John', 'class': 'Four', 'mark': 69, 'gender': 'female'}
21 {'id': 22, 'name': 'Reggid', 'class': 'Seven', 'mark': 55, 'gender': 'female'}
22 {'id': 23, 'name': 'Herod', 'class': 'Eight', 'mark': 79, 'gender': 'male'}
23 {'id': 24, 'name': 'Tiddy Now', 'class': 'Seven', 'mark': 78, 'gender': 'male'}
24 {'id': 25, 'name': 'Giff Tow', 'class': 'Seven', 'mark': 88, 'gender': 'male'}
25 {'id': 26, 'name': 'Crelea', 'class': 'Seven', 'mark': 79, 'gender': 'male'}
26 {'id': 27, 'name': nan, 'class': 'Three', 'mark': 81, 'gender': nan}
27 {'id': 28, 'name': 'Rojj Base', 'class': 'Seven', 'mark': 86, 'gender': 'female'}
28 {'id': 29, 'name': 'Tess Played', 'class': 'Seven', 'mark': 55, 'gender': 'male'}
29 {'id': 30, 'name': 'Reppy Red', 'class': 'Six', 'mark': 79, 'gender': 'female'}
30 {'id': 31, 'name': 'Marry Toeey', 'class': 'Four', 'mark': 88, 'gender': 'male'}
31 {'id': 32, 'name': 'Binn Rott', 'class': 'Seven', 'mark': 90, 'gender': 'female'}
32 {'id': 33, 'name': 'Kenn Rein', 'class': 'Six', 'mark': 96, 'gender': 'female'}
33 {'id': 34, 'name': 'Gain Toe', 'class': 'Seven', 'mark': 69, 'gender': 'male'}
34 {'id': 35, 'name': 'Rows Noump', 'class': 'Six', 'mark': 88, 'gender': 'female'}

In [ ]:
print(df[["id"]])

    id
0    1
1    2
2    3
3    4
4    5
..  ..
30  31
31  32
32  33
33  34
34  35

[35 rows x 1 columns]

In [ ]:
import pandas as pd

data = {
   'Name': ['Tom', 'Anna', 'Ravi', 'John'],
   'Age': [25, 30, 22, 28]
}

In [ ]:
df = pd.DataFrame(data, index=["A", "B", "C", "D"])

In [ ]:
print("loc single label:")
print(df.loc['A'])

loc single label:
Name    Tom
Age      25
Name: A, dtype: object

In [ ]:
print(df.loc[['A', 'B']])

   Name  Age
A   Tom   25
B  Anna   30

In [ ]:
print("\nloc slicing (A to C, both included):") # on a new line
print(df.loc['A':'C'])

loc slicing (A to C, both included):
   Name  Age
A   Tom   25
B  Anna   30
C  Ravi   22

In [ ]:
print(df.iloc[["1", "2", "3"]])

   Name  Age
B  Anna   30
C  Ravi   22
D  John   28

In [ ]:
df.head()

   Name  Age
A   Tom   25
B  Anna   30
C  Ravi   22
D  John   28

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/student.csv')

In [ ]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.iloc[:, 0]

0      1
1      2
2      3
3      4
4      5
      ..
30    31
31    32
32    33
33    34
34    35
Name: id, Length: 35, dtype: int64

In [ ]:
df.iloc[:, 2]

0      Four
1     Three
2     Three
3      Four
4      Four
      ...
30     Four
31    Seven
32      Six
33    Seven
34      Six
Name: class, Length: 35, dtype: object

In [ ]:
df[["name"]].head()   # rows for John Deo, Krish Star, Alex John

   id        name class  mark  gender
0   1    John Deo  Four    75  female
3   4  Krish Star  Four    60  female
5   6   Alex John  Four    55    male

In [ ]:
class Student:

    def __init__(self, name, mark):

       self.name = name

       self.mark = mark



  def passed(self, threshold):

    return self.mark >= threshold



threshold_mark = 75

students = []



for index, row in df.iterrows():

    s = Student(row['name'], row['mark'])

    students.append(s)



# Print every student with their pass status

pass_count = 0

fail_count = 0



for s in students:

    result = s.passed(threshold_mark)

    print(s.name, s.mark, result)

    if result:

        pass_count += 1

    else:

        fail_count += 1



print("\nTotal Passed (True):", pass_count)

print("Total Failed (False):", fail_count)

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 11)

In [ ]:
class Student:  # The template for a student

    def __init__(self, name, mark):

        self.name = name

        self.mark = mark



    def passed(self, threshold):  # Method to check if student passed

        return self.mark >= threshold



threshold_mark = 75

students = []



for index, row in df.iterrows():  # Go through the dataframe one row at a time

    s = Student(row['name'], row['mark'])

    students.append(s)



# Print every student with their pass status

pass_count = 0

fail_count = 0



for s in students:

    result = s.passed(threshold_mark)

    print(s.name, s.mark, result)

    if result:

        pass_count += 1

    else:

        fail_count += 1



print("\nTotal Passed (True):", pass_count)

print("Total Failed (False):", fail_count)

SyntaxError: invalid non-printable character U+202F (2836899713.py, line 1)

In [ ]:
df[df["mark"]> 80 .head()]

AttributeError: 'int' object has no attribute 'head'

In [ ]:
df.head()

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
df[df["mark"]> 80 & (df["gender"] == "female")].head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df[["name"]].head()

         name
0    John Deo
1    Max Ruin
2      Arnold
3  Krish Star
4   John Mike

In [ ]:
df

SyntaxError: invalid syntax (1453165618.py, line 1)

In [ ]:
df.iloc[[0, 1, 2]]

   id      name  class  mark  gender
0   1  John Deo   Four    75  female
1   2  Max Ruin  Three    85    male
2   3    Arnold  Three    55    male

In [ ]:
df[["name", "mark"]]

           name  mark
0      John Deo    75
1      Max Ruin    85
2        Arnold    55
3    Krish Star    60
4     John Mike    60
5     Alex John    55
6   My John Rob    78
7        Asruid    85
8       Tes Qry    78
9      Big John    55
10       Ronald    89
11        Recky    94
12          Kty    88
13         Bigy    88
14     Tade Row    88
15        Gimmy    88
16        Tumyu    54
17        Honny    75
18        Tinny    18
19       Jackly    65
20   Babby John    69
21       Reggid    55
22        Herod    79
23    Tiddy Now    78
24     Giff Tow    88
25       Crelea    79
26          NaN    81
27    Rojj Base    86
28  Tess Played    55
29    Reppy Red    79
30  Marry Toeey    88
31    Binn Rott    90
32    Kenn Rein    96
33     Gain Toe    69
34   Rows Noump    88

In [ ]:
df[df["class"] == "Four"]

    id         name class  mark  gender
0    1     John Deo  Four    75  female
3    4   Krish Star  Four    60  female
4    5    John Mike  Four    60  female
5    6    Alex John  Four    55    male
9   10     Big John  Four    55  female
15  16        Gimmy  Four    88    male
20  21   Babby John  Four    69  female
30  31  Marry Toeey  Four    88    male

In [ ]:
class Student:  # The template for a student
    def __init__(self, name, mark):
        self.name = name
        self.mark = mark

    def passed(self, threshold):  # Method to check if student passed
        return self.mark >= threshold

threshold_mark = 75
students = []

for index, row in df.iterrows():  # Go through the dataframe one row at a time
    s = Student(row['name'], row['mark'])
    students.append(s)

# Print every student with their pass status
pass_count = 0
fail_count = 0

for s in students:
    result = s.passed(threshold_mark)
    print(s.name, s.mark, result)
    if result:
        pass_count += 1
    else:
        fail_count += 1

print("\nTotal Passed (True):", pass_count)
print("Total Failed (False):", fail_count)

John Deo 75 True
Max Ruin 85 True
Arnold 55 False
Krish Star 60 False
John Mike 60 False
Alex John 55 False
My John Rob 78 True
Asruid 85 True
Tes Qry 78 True
Big John 55 False
Ronald 89 True
Recky 94 True
Kty 88 True
Bigy 88 True
Tade Row 88 True
Gimmy 88 True
Tumyu 54 False
Honny 75 True
Tinny 18 False
Jackly 65 False
Babby John 69 False
Reggid 55 False
Herod 79 True
Tiddy Now 78 True
Giff Tow 88 True
Crelea 79 True
nan 81 True
Rojj Base 86 True
Tess Played 55 False
Reppy Red 79 True
Marry Toeey 88 True
Binn Rott 90 True
Kenn Rein 96 True
Gain Toe 69 False
Rows Noump 88 True

Total Passed (True): 23
Total Failed (False): 12

In [ ]:
class Student:  # The template for a student
    def __init__(self, name, mark):
        self.name = name
        self.mark = mark

    def passed(self, threshold):  # Method to check if student passed
        return self.mark >= threshold

threshold_mark = 60
students = []

for index, row in df.iterrows():  # Go through the dataframe one row at a time
    s = Student(row['name'], row['mark'])
    students.append(s)

# Print every student with their pass status
pass_count = 0
fail_count = 0

for s in students:
    result = s.passed(threshold_mark)
    print(s.name, s.mark, result)
    if result:
        pass_count += 1
    else:
        fail_count += 1

print("\nTotal Passed (True):", pass_count)

KeyError: 'score'

In [ ]:
df['passed'] = df['mark'] >= 60

In [ ]:
df.head()

   id        name  class  mark  gender  passed
0   1    John Deo   Four    75  female    True
1   2    Max Ruin  Three    85    male    True
2   3      Arnold  Three    55    male   False
3   4  Krish Star   Four    60  female    True
4   5   John Mike   Four    60  female    True

In [ ]:
df = df.rename(columns={
    'mark':'score'
})

In [ ]:
df.head()

   id        name  class  score  gender  passed
0   1    John Deo   Four     75  female    True
1   2    Max Ruin  Three     85    male    True
2   3      Arnold  Three     55    male   False
3   4  Krish Star   Four     60  female    True
4   5   John Mike   Four     60  female    True

In [ ]:
df = df.drop(columns={"passed"})

In [ ]:
df.head()

   id        name  class  score  gender
0   1    John Deo   Four     75  female
1   2    Max Ruin  Three     85    male
2   3      Arnold  Three     55    male
3   4  Krish Star   Four     60  female
4   5   John Mike   Four     60  female

In [ ]:
df.groupby("class")["score"].mean()

class
Eight    79.000000
Fifth    78.000000
Five     80.000000
Four     68.750000
Nine     41.500000
Seven    77.600000
Six      82.571429
Three    73.666667
Name: score, dtype: float64

In [ ]:
df.groupby("class")["score"].count()

class
Eight     1
Fifth     1
Five      2
Four      8
Nine      2
Seven    10
Six       7
Three     3
Name: score, dtype: int64